/**
 * Regenerates docs/block-types.md from the block catalog, so the documentation
 * cannot drift from the schema. Run with: npx tsx scripts/generate-docs.mts
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  BLOCK_CATALOG,
  BLOCK_CATEGORIES,
  BLOCK_TYPES,
  EDGE_TYPES,
  EDGE_TYPE_INFO,
  type FieldDescriptor,
} from '../packages/core/src/index.js';

function fieldRow(field: FieldDescriptor, indent = ''): string[] {
  const shape =
    field.kind === 'recordList'
      ? `list of objects`
      : field.kind === 'stringList'
        ? 'list of strings'
        : field.kind === 'select'
          ? `one of ${(field.options ?? []).map((o) => `\`${o}\``).join(', ')}`
          : field.kind;

  const rows = [`${indent}| \`${field.key}\` | ${shape} | ${field.description} |`];
  for (const sub of field.fields ?? []) {
    rows.push(...fieldRow(sub, indent).map((r) => r.replace('| `', '| ↳ `')));
  }
  return rows;
}

const lines: string[] = [
  '# Block types',
  '',
  '<!-- Generated by scripts/generate-docs.mts — edit the catalog, not this file. -->',
  '',
  'Every block has a name, a summary, a description and a position. What differs is',
  'the `data` payload, which is typed per block type. That payload is what makes a',
  'diagram implementable rather than decorative.',
  '',
];

for (const category of BLOCK_CATEGORIES) {
  const types = BLOCK_TYPES.filter((t) => BLOCK_CATALOG[t].category === category.id);
  if (!types.length) continue;

  lines.push(`## ${category.label}`, '');
  for (const type of types) {
    const info = BLOCK_CATALOG[type];
    lines.push(
      `### ${info.icon} \`${type}\` — ${info.label}`,
      '',
      info.description,
      '',
      `**When to use it.** ${info.whenToUse}`,
      '',
      '| Field | Type | Description |',
      '| --- | --- | --- |',
      ...info.fields.flatMap((field) => fieldRow(field)),
      '',
    );
  }
}

lines.push(
  '## Connection types',
  '',
  'Connections are typed too. The validator uses the types to flag wiring that cannot',
  'be right — a data model does not "navigate" to a screen.',
  '',
  '| Type | Reads as | Meaning | Usually from | Usually to |',
  '| --- | --- | --- | --- | --- |',
);
for (const type of EDGE_TYPES) {
  const info = EDGE_TYPE_INFO[type];
  const list = (values: readonly string[] | null) =>
    values ? values.map((v) => `\`${v}\``).join(', ') : 'anything';
  lines.push(
    `| \`${type}\` | ${info.label} | ${info.description} | ${list(info.validSources)} | ${list(info.validTargets)} |`,
  );
}
lines.push('');

const out = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'block-types.md');
await writeFile(out, lines.join('\n'), 'utf8');
process.stdout.write(`Wrote ${out}\n`);
